complete exercise
aalvar0/Javascript-functions pull request #1
Opened 2023-11-19 16:58 UTC by aalvar0

2023-11-19 18:33 UTC, tictools commented
@aalvar0 : you missed adding function signatures using `JSDocs` convention.

FIX: add function signatures

2023-11-19 20:20 UTC, tictools requested changes

2023-11-19 20:20 UTC, tictools commented on exercise_02/getTotalWordsFromString.js
> +    const trimmedSentence = sentence.trim();
Do you know how does `trim` work? What does it return? 🤔

2023-11-19 20:20 UTC, tictools commented on exercise_07/isTypeOf.js
> +  switch (type) {
Avoid using `switch` when you can implement more simple logic using `if`.

FIX: needs work

2023-11-20 18:19 UTC, Manel0712 requested changes
In github actions, run the lint:fix script, and the lint script should be run, not lint:fix

2023-11-20 18:22 UTC, Manel0712 reviewed
NPM
Everything is well done

2023-11-20 18:27 UTC, Manel0712 reviewed
Modules
Everything is well done

2023-11-20 18:32 UTC, Manel0712 requested changes
Function description missing

2023-11-20 18:33 UTC, Manel0712 requested changes

2023-11-20 18:33 UTC, Manel0712 commented on exercise_02/getTotalWordsFromString.js
Function description missing

2023-11-20 18:35 UTC, Manel0712 requested changes

2023-11-20 18:35 UTC, Manel0712 commented on exercise_02/getTotalWordsFromString.js
> + *
Function description missing

2023-11-20 18:36 UTC, Manel0712 requested changes

2023-11-20 18:36 UTC, Manel0712 commented on exercise_02/getTotalWordsFromString.js
> + */
Function description missing

2023-11-20 18:42 UTC, Manel0712 requested changes

2023-11-20 18:42 UTC, Manel0712 commented on exercise_03/generateRandomNumberInRange.js
> + */
Function description missing

2023-11-20 18:42 UTC, Manel0712 commented on exercise_04/isGreaterThan.js
> + */
Function description missing

2023-11-20 18:42 UTC, Manel0712 commented on exercise_05/isAdditionGreaterThanFifty.js
> + */
Function description missing

2023-11-20 18:42 UTC, Manel0712 commented on exercise_06/checkCollectionHasElements.js
> + */
Function description missing

2023-11-20 18:42 UTC, Manel0712 commented on exercise_07/isTypeOf.js
> + */
Function description missing

2023-11-20 18:52 UTC, Manel0712 requested changes
Files are not formatted correctly

2023-11-20 19:17 UTC, Manel0712 approved these changes
Well Done!

2023-11-21 07:25 UTC, tictools requested changes

2023-11-21 07:25 UTC, tictools commented on package.json
FIX: Remove husky and lint-staged. Then merge

2023-11-21 07:26 UTC, tictools approved these changes

2023-11-21 18:31 UTC, merged